#!/bin/bash

# Initialization - DO NOT REMOVE
. helpers/initialize

##############################################################
### Customizations start here ################################
##############################################################

fail_if_not_root  # Comment out if 'root' is not required.

package python-software-properties
package software-properties-common
package_update
package 'unzip'
package 'curl'

# Suppress Java7 license prompt
echo debconf shared/accepted-oracle-license-v1-1 select true | \
  sudo debconf-set-selections

recipe 'mosh'
recipe 'oracle-java7'

add_line "export JAVA_HOME=/usr/lib/jvm/java-7-oracle" /etc/environment

# Install Go
wget https://go.googlecode.com/files/go1.2.linux-amd64.tar.gz
tar -C /usr/local -xzf go1.2.linux-amd64.tar.gz
mkdir $HOME/go
add_line "export GOPATH=$HOME/go" /etc/environment


# Install GVM
curl -s get.gvmtool.net | bash
source ~/.gvm/bin/gvm-init.sh
gvm install groovy
gvm install gradle

add_line "export GROOVY_HOME='~/.gvm/groovy/current/'" /etc/environment
add_line "export GRADLE_HOME='~/.gvm/gradle/current/'" /etc/environment
source /etc/environment

# Fail2Ban
package 'fail2ban'

# Automatic Security Updates
package unattended-upgrades
touch /etc/apt/apt.conf.d/10periodic
add_line 'APT::Periodic::Update-Package-Lists "1";' /etc/apt/apt.conf.d/10periodic
add_line 'APT::Periodic::Download-Upgradeable-Packages "1";' /etc/apt/apt.conf.d/10periodic
add_line 'APT::Periodic::AutocleanInterval "7";' /etc/apt/apt.conf.d/10periodic
add_line 'APT::Periodic::Unattended-Upgrade "1";' /etc/apt/apt.conf.d/10periodic

# Install Logwatch
package logwatch 
add_line "/usr/sbin/logwatch --output mail --mailto James.L.Williams@gmail.com --detail high" /etc/cron.daily/00logwatch

# Firewall
ufw allow 22
ufw allow 443
ufw allow 80
# Mosh ports
ufw allow proto udp to any port 60000:61000
ufw enable

package 'git-core'
package 'vim'
package 'build-essential'

# Install webfront
add_line "export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin" /etc/environment
source /etc/environment
go get github.com/nf/webfront
go install github.com/nf/webfront

### Show the Finished banner
finished

